
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'DE28BD825A3529F10904CE6D8241DF83'
    
_lr_action_items = {'LBRACE':([0,1,3,10,11,],[1,1,1,1,1,]),'CONSTANT':([0,1,3,10,11,],[2,2,2,2,2,]),'RBRACE':([2,5,6,7,8,12,13,14,15,],[-3,-6,-5,-8,12,-2,-1,-4,-7,]),'LSBRACKET':([0,1,3,10,11,],[3,3,3,3,3,]),'RSBRACKET':([2,5,6,7,9,12,13,14,15,],[-3,-6,-5,-8,13,-2,-1,-4,-7,]),'COMMA':([2,5,6,7,8,9,12,13,14,15,],[-3,-6,-5,-8,11,11,-2,-1,-4,-7,]),'KEYWORDS':([0,1,3,10,11,],[5,5,5,5,5,]),'COLON':([6,],[10,]),'$end':([2,4,5,6,12,13,14,],[-3,0,-6,-5,-2,-1,-4,]),'NORMSTRING':([0,1,3,10,11,],[6,6,6,6,6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'root_block':([0,1,3,10,11,],[4,7,7,14,15,]),'block_item_list':([1,3,],[8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> root_block","S'",1,None,None,None),
  ('root_block -> LSBRACKET block_item_list RSBRACKET','root_block',3,'p_root_block_1','file_parser.py',76),
  ('root_block -> LBRACE block_item_list RBRACE','root_block',3,'p_root_block_2','file_parser.py',81),
  ('root_block -> CONSTANT','root_block',1,'p_root_block_3','file_parser.py',86),
  ('root_block -> NORMSTRING COLON root_block','root_block',3,'p_root_block_3','file_parser.py',87),
  ('root_block -> NORMSTRING','root_block',1,'p_root_block_3','file_parser.py',88),
  ('root_block -> KEYWORDS','root_block',1,'p_root_block_3','file_parser.py',89),
  ('block_item_list -> block_item_list COMMA root_block','block_item_list',3,'p_block_item_list','file_parser.py',97),
  ('block_item_list -> root_block','block_item_list',1,'p_block_item_list','file_parser.py',98),
  ('empty -> <empty>','empty',0,'p_empty','file_parser.py',108),
]
